In [1]:
import numpy as np

In [3]:

list_ = [ '1','2','3','4','5' ]
array_list = np.array(list_)

In [7]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [16]:
# data type of array_list
array_list.dtype

dtype('<U1')

In [11]:
l = [ 1,2,3,4,5 ]
arr = np.array(l)

In [13]:
arr.dtype

dtype('int64')

In [17]:
#q.02-> print all element datatype
for i in array_list :
    print(i.dtype)

<U1
<U1
<U1
<U1
<U1


In [20]:
for j in list_:
    print (type(j))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [21]:
# q.03->
list_ = [ '1','2','3','4','5' ]
array_list = np.array( list_, dtype = int)

In [23]:
array_list.dtype

dtype('int64')

In [24]:
l = ['suh','lai']
a = np.array(l)

In [25]:
a

array(['suh', 'lai'], dtype='<U3')

In [26]:
# 4
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(num_list)

In [29]:
num_array
# 2d array

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
num_array.size
# total no of element 

6

In [32]:
num_array.shape
# matrix/array r shape ta debe means row,col debe 

(2, 3)

In [33]:
# q.05-> 3*3 matrix all zero
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
# idenetity matrix with dim 5*5
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
# alternative way
np.diag([1,1,1,1,1])

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])